language: c
os: linux
sudo: false
dist: trusty
env:
  - MINIFORGE_VERSION=4.8.2-1 CONDA_DIR=$HOME/mcf3 SHA256SUM=4f897e503bd0edfb277524ca5b6a5b14ad818b3198c2f07a36858b7d88c928db
before_install:
  - wget --quiet https://github.com/conda-forge/miniforge/releases/download/$MINIFORGE_VERSION/Miniforge3-$MINIFORGE_VERSION-Linux-x86_64.sh
  - echo "$SHA256SUM *Miniforge3-$MINIFORGE_VERSION-Linux-x86_64.sh" | sha256sum -c -
  - bash Miniforge3-$MINIFORGE_VERSION-Linux-x86_64.sh -fbp $CONDA_DIR
  - $CONDA_DIR/bin/conda install -yn base -c conda-forge conda
  - $CONDA_DIR/bin/conda env update -n base --file environment.yml
install:
  - source $CONDA_DIR/bin/activate && bash postBuild
script:
  - source $CONDA_DIR/bin/activate && jlpm test
