name: jupyterlab-fonts-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - beautysh
  - black
  - brotlipy
  - firefox
  - flake8
  - fonttools
  - geckodriver
  - jupyterlab >=1.2.2,<1.3
  - nodejs
  - python >=3.7,<3.8.0a0
  - robotframework-lint
  - robotframework-seleniumlibrary
