# This is used by repo2docker. conda can install all the Jupyter dependencies.
name: jupyterlab-fonts-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - brotlipy
  - flake8
  - fonttools
  - geckodriver
  - jupyterlab >=0.33,<0.34
  - nodejs >=8.9.3,<9
  - python >=3.6,<3.7
  - robotframework-lint
  - robotframework-seleniumlibrary
  - selenium =3.8.0
  - pip:
    - beautysh
